language: node_js
node_js: node
cache:
  directories:
  - node_modules
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: UyA13AXx4NmV7GsPnD/nduW0x/5a9yl/FPTBRtYkH+GJldKrj5XQDC7Tjt5iMbsmSxvwzl2CJZ8yYeSx/BsAfBdk3CfIp1X/M8FUuuk3UpPY6vrRHn/YXkFAE1spFP1n891A+rMpIrDehMJGa8t6cFe3eHAjYP0Ivl0e8wSsxRiGpBUBf6xJ/0sScBy0tfMr61Ot5+a+lqILEjiJDwOJmizS0JVj7RJv9Kd0dlimzwOA/oBmfq+WfV3SLwn0aq3g2SL/1QtHMP3KeJgFJ/jQoUdvj3TFwvd9Vq5akHF4NpiH4VIvC3dU8SUcziadXgZcCoJO1UM7wOk9FzJxFhO9F6/mca1J65wNyRVBjCufez82mImvM45xQ7sFjtD2Sd0wdMUCMK4kmpi4CdHSmRDaIDy9U9JLmWL+/NW0FXAi/6O15d2rjkwCnjNlCDXyyPsOFK77kzCnpuy75ourFz15gVi5k+NnTWBKy3liusE7ROY8k1lcUdmAeZA9XlNPnzSMK5gfk29SDWmUaYjDZ9R691DKLQLT0DDIXfGhH9U8rHhk5JeOj5q96gnRDgriXmlUkrFN6sB7Ef2CNBqnnrNnNceZk7d/eI7dxxYZYySheoQOXzpzNBsygyUa8Zod1/+crbYTHAyBlScQcCdUUpap9tMUr0Un69a7kgbf+MjjEzs=
  app: ThinkfulTrelloCIDrill
  on:
    repo: mulan114/ThinkfulTrelloCIDrill
